# Generated by Django 5.2.4 on 2025-08-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль Пользователь",
                "verbose_name_plural": "Профили Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите свой Telegram Chat ID",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
