# Generated by Django 5.2.4 on 2025-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="nickname",
        ),
    ]
