# Generated by Django 5.2.4 on 2025-08-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
