[pytest]
DJANGO_SETTINGS_MODULE=config.settings
[mypy]
ignore_missing_imports = True
files = !users/tests/, !habits/tests/, !telegram_bot/tests/
[mypy-rest_framework.*]
ignore_missing_imports = True
[mypy-django.*]
ignore_missing_imports = True
[mypy-telegram_bot.tests.*]
ignore_missing_imports = True
[mypy-users.tests.*]
ignore_missing_imports = True
[mypy-habits.tests.*]
ignore_missing_imports = True
