# Generated by Django 5.2.4 on 2025-07-29 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyHabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Выполнено"), ("skipped", "Пропущено")],
                        default="done",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Примечание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_completed",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время выполнения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ежедневный лог привычки",
                "verbose_name_plural": "Ежедневные логи привычек",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("custom", "Выборочные дни"),
                        ],
                        default="daily",
                        max_length=50,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "selected_weekdays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Выбранные дни недели (например, ['пн', 'ср', 'пт'])",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку.",
                        max_length=255,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="Цвет"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=30, verbose_name="Иконка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "planned_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Плановое время"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд)",
                        verbose_name="Время на выполнение (секунды)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения (текстовое описание)",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="HabitCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория привычки",
                "verbose_name_plural": "Категории привычек",
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата выполнения")),
                (
                    "is_done",
                    models.BooleanField(default=True, verbose_name="Выполнено"),
                ),
            ],
            options={
                "verbose_name": "Лог привычки",
                "verbose_name_plural": "Логи привычек",
            },
        ),
        migrations.CreateModel(
            name="HabitTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("success", "Успех"),
                            ("fail", "Неуспех"),
                            ("paused", "Пауза"),
                        ],
                        default="in_progress",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(default=0, verbose_name="Прогресс (%)"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "reason",
                    models.TextField(
                        blank=True, verbose_name="Причина (неуспех, завершение и т.д.)"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="Архивирована"),
                ),
            ],
            options={
                "verbose_name": "Отслеживание привычки",
                "verbose_name_plural": "Отслеживания привычек",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст уведомления")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("email", "Email")],
                        max_length=20,
                        verbose_name="Канал",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Напоминание о привычке"),
                            ("congratulation", "Поздравление с выполнением"),
                            ("info", "Информационное сообщение"),
                            ("warning", "Предупреждение"),
                            ("inactive_reminder", "Напоминание о неактивности"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "notification_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок уведомления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание награды"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда",
                "verbose_name_plural": "Награды",
            },
        ),
    ]
