# Generated by Django 5.2.4 on 2025-08-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habitlog_last_reminded_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habitcategory",
            options={
                "verbose_name": "Категория Привычка",
                "verbose_name_plural": "Категории Привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[("daily", "Ежедневно"), ("custom", "Выборочные дни")],
                default="daily",
                max_length=50,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с другой привычкой (должна быть приятной привычкой)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="useful_habits",
                to="habits.habit",
                verbose_name="Привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Чем пользователь должен себя вознаградить после выполнения (текстовое описание)",
                max_length=255,
                verbose_name="Вознаграждение",
            ),
            preserve_default=False,
        ),
    ]
