# Generated by Django 5.2.4 on 2025-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habitcategory_options_alter_habit_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habitcategory",
            options={
                "verbose_name": "Категория привычки",
                "verbose_name_plural": "Категории привычек",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст уведомления"
            ),
        ),
    ]
