# Generated by Django 5.2.4 on 2025-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habitcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reminder", "Напоминание о привычке"),
                    ("congratulation", "Поздравление с выполнением"),
                    ("info", "Информационное сообщение"),
                    ("warning", "Предупреждение"),
                    ("inactive_reminder", "Напоминание о неактивности"),
                ],
                max_length=20,
                null=True,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
