# Generated by Django 5.2.4 on 2025-08-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Заголовок уведомления",
            ),
        ),
    ]
