# Generated by Django 5.2.4 on 2025-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_alter_notification_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Чем пользователь должен себя вознаградить после выполнения (текстовое описание)",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
