# Generated by Django 5.2.4 on 2025-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.CharField(max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Входящее"), ("out", "Исходящее")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TelegramIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_chat_id", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
